# Copyright (c) 2018, NVIDIA CORPORATION.

dist: trusty
sudo: required
language: python

branches:
    only:
        - master
env:
  global:
  - secure: TDc+mrzcaUpmVzxXgZL5CP+y98sKfziivgAfriuszokkJAQmsktjMua0nYqQv0hp4ZRJUN5PuZT/Q1a1G4eZ7FxP30t7rA7hSNXPSbWg46nZv016GMhFQQ1tR9VSL91pFECcvMFARpm2pfSS+9PYFg+qyADFPcBLznnHlE69floYfFuhr2h4dhq05fSOjHY3HFpfS9QxBhglWD5ei2BBI/OI5ZXkKeS/Jk/xzWzBx7HdPP+CM4826XhSwxYN5WsjuqNn+FvMYOTkY0JSJQDwpUx27ag3t3K9+MKCRQ9ZoBDlMcgVx1ZQYQbv3s4sNO1+yVgvl1tM1ETBuugVy64lhppWIkcq8QAVJKAqakmEYTlXqH9n+qHeQGmt0PKtsbnLT6Fghdm+hVhh9WjOelI3E2AZGCN6IGYYHpyoTtHE7puBzSplrobtg1zc3CbKLDgsBz06Jvuic8QQPVhtP/wRcSWfLGSoyFgV68Y9ItkgMTmtsJX4hzxm+O76CoSixJj7vn3Og3HCPKVlzEWV7QelaYJLMKZHXgmkJwxwJXtsg4Yp++2ttzGN9q+m6cfJJiNFNC9UOvIXMww9jb+k/y3npHyFKaCmBQudMkTfHEw14PyfdKJCE9insUQnYIV/XqlKWabD195m2g0vtoBYgwiCdEqXESLCysm2Q1fqI9TAFfI=

matrix:
  include:
    - env: CUDA=9.2.148_396.37 PYTHON=3.5 LABEL_MAIN=1 BUILD_CUML=1
    - env: CUDA=9.2.148_396.37 PYTHON=3.6 LABEL_MAIN=1
    - env: CUDA=10.0.130_410.48 PYTHON=3.5 BUILD_CUML=1
    - env: CUDA=10.0.130_410.48 PYTHON=3.6

before_install:
  # install build environment for libgdf
  - source ./travisci/install-env.sh
  # install miniconda
  - travis_retry wget --progress=dot:mega https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH

install:
  # check
  - conda --version
  # install conda build
  - conda install conda-build anaconda-client flake8 conda-verify cmake=3.11.* --yes
script:
  # Activate root environment for cmake
  - source activate root
  # check conda versions
  - conda list
  # build cuML
  - source ./travisci/build_cuml.sh
  - flake8

after_success:
  # upload cuML
  - source ./travisci/upload-anaconda.sh
